// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"giteaApiClientGenerated/models"
)

// OrgListTeamRepoReader is a Reader for the OrgListTeamRepo structure.
type OrgListTeamRepoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgListTeamRepoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgListTeamRepoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewOrgListTeamRepoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /teams/{id}/repos/{org}/{repo}] orgListTeamRepo", response, response.Code())
	}
}

// NewOrgListTeamRepoOK creates a OrgListTeamRepoOK with default headers values
func NewOrgListTeamRepoOK() *OrgListTeamRepoOK {
	return &OrgListTeamRepoOK{}
}

/*
OrgListTeamRepoOK describes a response with status code 200, with default header values.

Repository
*/
type OrgListTeamRepoOK struct {
	Payload *models.Repository
}

// IsSuccess returns true when this org list team repo o k response has a 2xx status code
func (o *OrgListTeamRepoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this org list team repo o k response has a 3xx status code
func (o *OrgListTeamRepoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this org list team repo o k response has a 4xx status code
func (o *OrgListTeamRepoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this org list team repo o k response has a 5xx status code
func (o *OrgListTeamRepoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this org list team repo o k response a status code equal to that given
func (o *OrgListTeamRepoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the org list team repo o k response
func (o *OrgListTeamRepoOK) Code() int {
	return 200
}

func (o *OrgListTeamRepoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}/repos/{org}/{repo}][%d] orgListTeamRepoOK %s", 200, payload)
}

func (o *OrgListTeamRepoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}/repos/{org}/{repo}][%d] orgListTeamRepoOK %s", 200, payload)
}

func (o *OrgListTeamRepoOK) GetPayload() *models.Repository {
	return o.Payload
}

func (o *OrgListTeamRepoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Repository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrgListTeamRepoNotFound creates a OrgListTeamRepoNotFound with default headers values
func NewOrgListTeamRepoNotFound() *OrgListTeamRepoNotFound {
	return &OrgListTeamRepoNotFound{}
}

/*
OrgListTeamRepoNotFound describes a response with status code 404, with default header values.

APINotFound is a not found empty response
*/
type OrgListTeamRepoNotFound struct {
}

// IsSuccess returns true when this org list team repo not found response has a 2xx status code
func (o *OrgListTeamRepoNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this org list team repo not found response has a 3xx status code
func (o *OrgListTeamRepoNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this org list team repo not found response has a 4xx status code
func (o *OrgListTeamRepoNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this org list team repo not found response has a 5xx status code
func (o *OrgListTeamRepoNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this org list team repo not found response a status code equal to that given
func (o *OrgListTeamRepoNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the org list team repo not found response
func (o *OrgListTeamRepoNotFound) Code() int {
	return 404
}

func (o *OrgListTeamRepoNotFound) Error() string {
	return fmt.Sprintf("[GET /teams/{id}/repos/{org}/{repo}][%d] orgListTeamRepoNotFound", 404)
}

func (o *OrgListTeamRepoNotFound) String() string {
	return fmt.Sprintf("[GET /teams/{id}/repos/{org}/{repo}][%d] orgListTeamRepoNotFound", 404)
}

func (o *OrgListTeamRepoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
