// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Raidflux/gitea-api-client-generated/giteaApiClientGenerated/models"
)

// OrgGetHookReader is a Reader for the OrgGetHook structure.
type OrgGetHookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgGetHookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgGetHookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewOrgGetHookNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /orgs/{org}/hooks/{id}] orgGetHook", response, response.Code())
	}
}

// NewOrgGetHookOK creates a OrgGetHookOK with default headers values
func NewOrgGetHookOK() *OrgGetHookOK {
	return &OrgGetHookOK{}
}

/*
OrgGetHookOK describes a response with status code 200, with default header values.

Hook
*/
type OrgGetHookOK struct {
	Payload *models.Hook
}

// IsSuccess returns true when this org get hook o k response has a 2xx status code
func (o *OrgGetHookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this org get hook o k response has a 3xx status code
func (o *OrgGetHookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this org get hook o k response has a 4xx status code
func (o *OrgGetHookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this org get hook o k response has a 5xx status code
func (o *OrgGetHookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this org get hook o k response a status code equal to that given
func (o *OrgGetHookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the org get hook o k response
func (o *OrgGetHookOK) Code() int {
	return 200
}

func (o *OrgGetHookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{org}/hooks/{id}][%d] orgGetHookOK %s", 200, payload)
}

func (o *OrgGetHookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{org}/hooks/{id}][%d] orgGetHookOK %s", 200, payload)
}

func (o *OrgGetHookOK) GetPayload() *models.Hook {
	return o.Payload
}

func (o *OrgGetHookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Hook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrgGetHookNotFound creates a OrgGetHookNotFound with default headers values
func NewOrgGetHookNotFound() *OrgGetHookNotFound {
	return &OrgGetHookNotFound{}
}

/*
OrgGetHookNotFound describes a response with status code 404, with default header values.

APINotFound is a not found empty response
*/
type OrgGetHookNotFound struct {
}

// IsSuccess returns true when this org get hook not found response has a 2xx status code
func (o *OrgGetHookNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this org get hook not found response has a 3xx status code
func (o *OrgGetHookNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this org get hook not found response has a 4xx status code
func (o *OrgGetHookNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this org get hook not found response has a 5xx status code
func (o *OrgGetHookNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this org get hook not found response a status code equal to that given
func (o *OrgGetHookNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the org get hook not found response
func (o *OrgGetHookNotFound) Code() int {
	return 404
}

func (o *OrgGetHookNotFound) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/hooks/{id}][%d] orgGetHookNotFound", 404)
}

func (o *OrgGetHookNotFound) String() string {
	return fmt.Sprintf("[GET /orgs/{org}/hooks/{id}][%d] orgGetHookNotFound", 404)
}

func (o *OrgGetHookNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
