// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrganizationUnblockUserParams creates a new OrganizationUnblockUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrganizationUnblockUserParams() *OrganizationUnblockUserParams {
	return &OrganizationUnblockUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrganizationUnblockUserParamsWithTimeout creates a new OrganizationUnblockUserParams object
// with the ability to set a timeout on a request.
func NewOrganizationUnblockUserParamsWithTimeout(timeout time.Duration) *OrganizationUnblockUserParams {
	return &OrganizationUnblockUserParams{
		timeout: timeout,
	}
}

// NewOrganizationUnblockUserParamsWithContext creates a new OrganizationUnblockUserParams object
// with the ability to set a context for a request.
func NewOrganizationUnblockUserParamsWithContext(ctx context.Context) *OrganizationUnblockUserParams {
	return &OrganizationUnblockUserParams{
		Context: ctx,
	}
}

// NewOrganizationUnblockUserParamsWithHTTPClient creates a new OrganizationUnblockUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrganizationUnblockUserParamsWithHTTPClient(client *http.Client) *OrganizationUnblockUserParams {
	return &OrganizationUnblockUserParams{
		HTTPClient: client,
	}
}

/*
OrganizationUnblockUserParams contains all the parameters to send to the API endpoint

	for the organization unblock user operation.

	Typically these are written to a http.Request.
*/
type OrganizationUnblockUserParams struct {

	/* Org.

	   name of the organization
	*/
	Org string

	/* Username.

	   user to unblock
	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the organization unblock user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationUnblockUserParams) WithDefaults() *OrganizationUnblockUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the organization unblock user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationUnblockUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the organization unblock user params
func (o *OrganizationUnblockUserParams) WithTimeout(timeout time.Duration) *OrganizationUnblockUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the organization unblock user params
func (o *OrganizationUnblockUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the organization unblock user params
func (o *OrganizationUnblockUserParams) WithContext(ctx context.Context) *OrganizationUnblockUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the organization unblock user params
func (o *OrganizationUnblockUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the organization unblock user params
func (o *OrganizationUnblockUserParams) WithHTTPClient(client *http.Client) *OrganizationUnblockUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the organization unblock user params
func (o *OrganizationUnblockUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrg adds the org to the organization unblock user params
func (o *OrganizationUnblockUserParams) WithOrg(org string) *OrganizationUnblockUserParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the organization unblock user params
func (o *OrganizationUnblockUserParams) SetOrg(org string) {
	o.Org = org
}

// WithUsername adds the username to the organization unblock user params
func (o *OrganizationUnblockUserParams) WithUsername(username string) *OrganizationUnblockUserParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the organization unblock user params
func (o *OrganizationUnblockUserParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *OrganizationUnblockUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
