// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UserCurrentDeleteFollowReader is a Reader for the UserCurrentDeleteFollow structure.
type UserCurrentDeleteFollowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserCurrentDeleteFollowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUserCurrentDeleteFollowNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUserCurrentDeleteFollowNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /user/following/{username}] userCurrentDeleteFollow", response, response.Code())
	}
}

// NewUserCurrentDeleteFollowNoContent creates a UserCurrentDeleteFollowNoContent with default headers values
func NewUserCurrentDeleteFollowNoContent() *UserCurrentDeleteFollowNoContent {
	return &UserCurrentDeleteFollowNoContent{}
}

/*
UserCurrentDeleteFollowNoContent describes a response with status code 204, with default header values.

APIEmpty is an empty response
*/
type UserCurrentDeleteFollowNoContent struct {
}

// IsSuccess returns true when this user current delete follow no content response has a 2xx status code
func (o *UserCurrentDeleteFollowNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this user current delete follow no content response has a 3xx status code
func (o *UserCurrentDeleteFollowNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this user current delete follow no content response has a 4xx status code
func (o *UserCurrentDeleteFollowNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this user current delete follow no content response has a 5xx status code
func (o *UserCurrentDeleteFollowNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this user current delete follow no content response a status code equal to that given
func (o *UserCurrentDeleteFollowNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the user current delete follow no content response
func (o *UserCurrentDeleteFollowNoContent) Code() int {
	return 204
}

func (o *UserCurrentDeleteFollowNoContent) Error() string {
	return fmt.Sprintf("[DELETE /user/following/{username}][%d] userCurrentDeleteFollowNoContent", 204)
}

func (o *UserCurrentDeleteFollowNoContent) String() string {
	return fmt.Sprintf("[DELETE /user/following/{username}][%d] userCurrentDeleteFollowNoContent", 204)
}

func (o *UserCurrentDeleteFollowNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUserCurrentDeleteFollowNotFound creates a UserCurrentDeleteFollowNotFound with default headers values
func NewUserCurrentDeleteFollowNotFound() *UserCurrentDeleteFollowNotFound {
	return &UserCurrentDeleteFollowNotFound{}
}

/*
UserCurrentDeleteFollowNotFound describes a response with status code 404, with default header values.

APINotFound is a not found empty response
*/
type UserCurrentDeleteFollowNotFound struct {
}

// IsSuccess returns true when this user current delete follow not found response has a 2xx status code
func (o *UserCurrentDeleteFollowNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this user current delete follow not found response has a 3xx status code
func (o *UserCurrentDeleteFollowNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this user current delete follow not found response has a 4xx status code
func (o *UserCurrentDeleteFollowNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this user current delete follow not found response has a 5xx status code
func (o *UserCurrentDeleteFollowNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this user current delete follow not found response a status code equal to that given
func (o *UserCurrentDeleteFollowNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the user current delete follow not found response
func (o *UserCurrentDeleteFollowNotFound) Code() int {
	return 404
}

func (o *UserCurrentDeleteFollowNotFound) Error() string {
	return fmt.Sprintf("[DELETE /user/following/{username}][%d] userCurrentDeleteFollowNotFound", 404)
}

func (o *UserCurrentDeleteFollowNotFound) String() string {
	return fmt.Sprintf("[DELETE /user/following/{username}][%d] userCurrentDeleteFollowNotFound", 404)
}

func (o *UserCurrentDeleteFollowNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
