// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"giteaApiClientGenerated/models"
)

// UserListBlocksReader is a Reader for the UserListBlocks structure.
type UserListBlocksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserListBlocksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserListBlocksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /user/blocks] userListBlocks", response, response.Code())
	}
}

// NewUserListBlocksOK creates a UserListBlocksOK with default headers values
func NewUserListBlocksOK() *UserListBlocksOK {
	return &UserListBlocksOK{}
}

/*
UserListBlocksOK describes a response with status code 200, with default header values.

UserList
*/
type UserListBlocksOK struct {
	Payload []*models.User
}

// IsSuccess returns true when this user list blocks o k response has a 2xx status code
func (o *UserListBlocksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this user list blocks o k response has a 3xx status code
func (o *UserListBlocksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this user list blocks o k response has a 4xx status code
func (o *UserListBlocksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this user list blocks o k response has a 5xx status code
func (o *UserListBlocksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this user list blocks o k response a status code equal to that given
func (o *UserListBlocksOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the user list blocks o k response
func (o *UserListBlocksOK) Code() int {
	return 200
}

func (o *UserListBlocksOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /user/blocks][%d] userListBlocksOK %s", 200, payload)
}

func (o *UserListBlocksOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /user/blocks][%d] userListBlocksOK %s", 200, payload)
}

func (o *UserListBlocksOK) GetPayload() []*models.User {
	return o.Payload
}

func (o *UserListBlocksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
