// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"giteaApiClientGenerated/models"
)

// RepoGetByIDReader is a Reader for the RepoGetByID structure.
type RepoGetByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoGetByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoGetByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRepoGetByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /repositories/{id}] repoGetByID", response, response.Code())
	}
}

// NewRepoGetByIDOK creates a RepoGetByIDOK with default headers values
func NewRepoGetByIDOK() *RepoGetByIDOK {
	return &RepoGetByIDOK{}
}

/*
RepoGetByIDOK describes a response with status code 200, with default header values.

Repository
*/
type RepoGetByIDOK struct {
	Payload *models.Repository
}

// IsSuccess returns true when this repo get by Id o k response has a 2xx status code
func (o *RepoGetByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this repo get by Id o k response has a 3xx status code
func (o *RepoGetByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repo get by Id o k response has a 4xx status code
func (o *RepoGetByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this repo get by Id o k response has a 5xx status code
func (o *RepoGetByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this repo get by Id o k response a status code equal to that given
func (o *RepoGetByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the repo get by Id o k response
func (o *RepoGetByIDOK) Code() int {
	return 200
}

func (o *RepoGetByIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repositories/{id}][%d] repoGetByIdOK %s", 200, payload)
}

func (o *RepoGetByIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repositories/{id}][%d] repoGetByIdOK %s", 200, payload)
}

func (o *RepoGetByIDOK) GetPayload() *models.Repository {
	return o.Payload
}

func (o *RepoGetByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Repository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepoGetByIDNotFound creates a RepoGetByIDNotFound with default headers values
func NewRepoGetByIDNotFound() *RepoGetByIDNotFound {
	return &RepoGetByIDNotFound{}
}

/*
RepoGetByIDNotFound describes a response with status code 404, with default header values.

APINotFound is a not found empty response
*/
type RepoGetByIDNotFound struct {
}

// IsSuccess returns true when this repo get by Id not found response has a 2xx status code
func (o *RepoGetByIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this repo get by Id not found response has a 3xx status code
func (o *RepoGetByIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this repo get by Id not found response has a 4xx status code
func (o *RepoGetByIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this repo get by Id not found response has a 5xx status code
func (o *RepoGetByIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this repo get by Id not found response a status code equal to that given
func (o *RepoGetByIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the repo get by Id not found response
func (o *RepoGetByIDNotFound) Code() int {
	return 404
}

func (o *RepoGetByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /repositories/{id}][%d] repoGetByIdNotFound", 404)
}

func (o *RepoGetByIDNotFound) String() string {
	return fmt.Sprintf("[GET /repositories/{id}][%d] repoGetByIdNotFound", 404)
}

func (o *RepoGetByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
