// Code generated by go-swagger; DO NOT EDIT.

package miscellaneous

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Raidflux/gitea-api-client-generated/giteaApiClientGenerated/models"
)

// GetGitignoreTemplateInfoReader is a Reader for the GetGitignoreTemplateInfo structure.
type GetGitignoreTemplateInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGitignoreTemplateInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGitignoreTemplateInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetGitignoreTemplateInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /gitignore/templates/{name}] getGitignoreTemplateInfo", response, response.Code())
	}
}

// NewGetGitignoreTemplateInfoOK creates a GetGitignoreTemplateInfoOK with default headers values
func NewGetGitignoreTemplateInfoOK() *GetGitignoreTemplateInfoOK {
	return &GetGitignoreTemplateInfoOK{}
}

/*
GetGitignoreTemplateInfoOK describes a response with status code 200, with default header values.

GitignoreTemplateInfo
*/
type GetGitignoreTemplateInfoOK struct {
	Payload *models.GitignoreTemplateInfo
}

// IsSuccess returns true when this get gitignore template info o k response has a 2xx status code
func (o *GetGitignoreTemplateInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get gitignore template info o k response has a 3xx status code
func (o *GetGitignoreTemplateInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gitignore template info o k response has a 4xx status code
func (o *GetGitignoreTemplateInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get gitignore template info o k response has a 5xx status code
func (o *GetGitignoreTemplateInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get gitignore template info o k response a status code equal to that given
func (o *GetGitignoreTemplateInfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get gitignore template info o k response
func (o *GetGitignoreTemplateInfoOK) Code() int {
	return 200
}

func (o *GetGitignoreTemplateInfoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /gitignore/templates/{name}][%d] getGitignoreTemplateInfoOK %s", 200, payload)
}

func (o *GetGitignoreTemplateInfoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /gitignore/templates/{name}][%d] getGitignoreTemplateInfoOK %s", 200, payload)
}

func (o *GetGitignoreTemplateInfoOK) GetPayload() *models.GitignoreTemplateInfo {
	return o.Payload
}

func (o *GetGitignoreTemplateInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GitignoreTemplateInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGitignoreTemplateInfoNotFound creates a GetGitignoreTemplateInfoNotFound with default headers values
func NewGetGitignoreTemplateInfoNotFound() *GetGitignoreTemplateInfoNotFound {
	return &GetGitignoreTemplateInfoNotFound{}
}

/*
GetGitignoreTemplateInfoNotFound describes a response with status code 404, with default header values.

APINotFound is a not found empty response
*/
type GetGitignoreTemplateInfoNotFound struct {
}

// IsSuccess returns true when this get gitignore template info not found response has a 2xx status code
func (o *GetGitignoreTemplateInfoNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get gitignore template info not found response has a 3xx status code
func (o *GetGitignoreTemplateInfoNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gitignore template info not found response has a 4xx status code
func (o *GetGitignoreTemplateInfoNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get gitignore template info not found response has a 5xx status code
func (o *GetGitignoreTemplateInfoNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get gitignore template info not found response a status code equal to that given
func (o *GetGitignoreTemplateInfoNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get gitignore template info not found response
func (o *GetGitignoreTemplateInfoNotFound) Code() int {
	return 404
}

func (o *GetGitignoreTemplateInfoNotFound) Error() string {
	return fmt.Sprintf("[GET /gitignore/templates/{name}][%d] getGitignoreTemplateInfoNotFound", 404)
}

func (o *GetGitignoreTemplateInfoNotFound) String() string {
	return fmt.Sprintf("[GET /gitignore/templates/{name}][%d] getGitignoreTemplateInfoNotFound", 404)
}

func (o *GetGitignoreTemplateInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
