// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"giteaApiClientGenerated/models"
)

// NotifyReadListReader is a Reader for the NotifyReadList structure.
type NotifyReadListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotifyReadListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 205:
		result := NewNotifyReadListResetContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /notifications] notifyReadList", response, response.Code())
	}
}

// NewNotifyReadListResetContent creates a NotifyReadListResetContent with default headers values
func NewNotifyReadListResetContent() *NotifyReadListResetContent {
	return &NotifyReadListResetContent{}
}

/*
NotifyReadListResetContent describes a response with status code 205, with default header values.

NotificationThreadList
*/
type NotifyReadListResetContent struct {
	Payload []*models.NotificationThread
}

// IsSuccess returns true when this notify read list reset content response has a 2xx status code
func (o *NotifyReadListResetContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this notify read list reset content response has a 3xx status code
func (o *NotifyReadListResetContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this notify read list reset content response has a 4xx status code
func (o *NotifyReadListResetContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this notify read list reset content response has a 5xx status code
func (o *NotifyReadListResetContent) IsServerError() bool {
	return false
}

// IsCode returns true when this notify read list reset content response a status code equal to that given
func (o *NotifyReadListResetContent) IsCode(code int) bool {
	return code == 205
}

// Code gets the status code for the notify read list reset content response
func (o *NotifyReadListResetContent) Code() int {
	return 205
}

func (o *NotifyReadListResetContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /notifications][%d] notifyReadListResetContent %s", 205, payload)
}

func (o *NotifyReadListResetContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /notifications][%d] notifyReadListResetContent %s", 205, payload)
}

func (o *NotifyReadListResetContent) GetPayload() []*models.NotificationThread {
	return o.Payload
}

func (o *NotifyReadListResetContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
