// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNotifyGetThreadParams creates a new NotifyGetThreadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNotifyGetThreadParams() *NotifyGetThreadParams {
	return &NotifyGetThreadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNotifyGetThreadParamsWithTimeout creates a new NotifyGetThreadParams object
// with the ability to set a timeout on a request.
func NewNotifyGetThreadParamsWithTimeout(timeout time.Duration) *NotifyGetThreadParams {
	return &NotifyGetThreadParams{
		timeout: timeout,
	}
}

// NewNotifyGetThreadParamsWithContext creates a new NotifyGetThreadParams object
// with the ability to set a context for a request.
func NewNotifyGetThreadParamsWithContext(ctx context.Context) *NotifyGetThreadParams {
	return &NotifyGetThreadParams{
		Context: ctx,
	}
}

// NewNotifyGetThreadParamsWithHTTPClient creates a new NotifyGetThreadParams object
// with the ability to set a custom HTTPClient for a request.
func NewNotifyGetThreadParamsWithHTTPClient(client *http.Client) *NotifyGetThreadParams {
	return &NotifyGetThreadParams{
		HTTPClient: client,
	}
}

/*
NotifyGetThreadParams contains all the parameters to send to the API endpoint

	for the notify get thread operation.

	Typically these are written to a http.Request.
*/
type NotifyGetThreadParams struct {

	/* ID.

	   id of notification thread
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the notify get thread params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotifyGetThreadParams) WithDefaults() *NotifyGetThreadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the notify get thread params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotifyGetThreadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the notify get thread params
func (o *NotifyGetThreadParams) WithTimeout(timeout time.Duration) *NotifyGetThreadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notify get thread params
func (o *NotifyGetThreadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notify get thread params
func (o *NotifyGetThreadParams) WithContext(ctx context.Context) *NotifyGetThreadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notify get thread params
func (o *NotifyGetThreadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notify get thread params
func (o *NotifyGetThreadParams) WithHTTPClient(client *http.Client) *NotifyGetThreadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notify get thread params
func (o *NotifyGetThreadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the notify get thread params
func (o *NotifyGetThreadParams) WithID(id string) *NotifyGetThreadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the notify get thread params
func (o *NotifyGetThreadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *NotifyGetThreadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
