// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserBadgeOption UserBadgeOption options for link between users and badges
//
// swagger:model UserBadgeOption
type UserBadgeOption struct {

	// badge slugs
	// Example: ["badge1","badge2"]
	BadgeSlugs []string `json:"badge_slugs"`
}

// Validate validates this user badge option
func (m *UserBadgeOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user badge option based on context it is used
func (m *UserBadgeOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserBadgeOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserBadgeOption) UnmarshalBinary(b []byte) error {
	var res UserBadgeOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
