// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Raidflux/gitea-api-client-generated/giteaApiClientGenerated/models"
)

// IssueListLabelsReader is a Reader for the IssueListLabels structure.
type IssueListLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IssueListLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIssueListLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewIssueListLabelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /repos/{owner}/{repo}/labels] issueListLabels", response, response.Code())
	}
}

// NewIssueListLabelsOK creates a IssueListLabelsOK with default headers values
func NewIssueListLabelsOK() *IssueListLabelsOK {
	return &IssueListLabelsOK{}
}

/*
IssueListLabelsOK describes a response with status code 200, with default header values.

LabelList
*/
type IssueListLabelsOK struct {
	Payload []*models.Label
}

// IsSuccess returns true when this issue list labels o k response has a 2xx status code
func (o *IssueListLabelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this issue list labels o k response has a 3xx status code
func (o *IssueListLabelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this issue list labels o k response has a 4xx status code
func (o *IssueListLabelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this issue list labels o k response has a 5xx status code
func (o *IssueListLabelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this issue list labels o k response a status code equal to that given
func (o *IssueListLabelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the issue list labels o k response
func (o *IssueListLabelsOK) Code() int {
	return 200
}

func (o *IssueListLabelsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/labels][%d] issueListLabelsOK %s", 200, payload)
}

func (o *IssueListLabelsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/labels][%d] issueListLabelsOK %s", 200, payload)
}

func (o *IssueListLabelsOK) GetPayload() []*models.Label {
	return o.Payload
}

func (o *IssueListLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIssueListLabelsNotFound creates a IssueListLabelsNotFound with default headers values
func NewIssueListLabelsNotFound() *IssueListLabelsNotFound {
	return &IssueListLabelsNotFound{}
}

/*
IssueListLabelsNotFound describes a response with status code 404, with default header values.

APINotFound is a not found empty response
*/
type IssueListLabelsNotFound struct {
}

// IsSuccess returns true when this issue list labels not found response has a 2xx status code
func (o *IssueListLabelsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this issue list labels not found response has a 3xx status code
func (o *IssueListLabelsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this issue list labels not found response has a 4xx status code
func (o *IssueListLabelsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this issue list labels not found response has a 5xx status code
func (o *IssueListLabelsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this issue list labels not found response a status code equal to that given
func (o *IssueListLabelsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the issue list labels not found response
func (o *IssueListLabelsNotFound) Code() int {
	return 404
}

func (o *IssueListLabelsNotFound) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/labels][%d] issueListLabelsNotFound", 404)
}

func (o *IssueListLabelsNotFound) String() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/labels][%d] issueListLabelsNotFound", 404)
}

func (o *IssueListLabelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
