// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"giteaApiClientGenerated/models"
)

// IssueGetLabelsReader is a Reader for the IssueGetLabels structure.
type IssueGetLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IssueGetLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIssueGetLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewIssueGetLabelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /repos/{owner}/{repo}/issues/{index}/labels] issueGetLabels", response, response.Code())
	}
}

// NewIssueGetLabelsOK creates a IssueGetLabelsOK with default headers values
func NewIssueGetLabelsOK() *IssueGetLabelsOK {
	return &IssueGetLabelsOK{}
}

/*
IssueGetLabelsOK describes a response with status code 200, with default header values.

LabelList
*/
type IssueGetLabelsOK struct {
	Payload []*models.Label
}

// IsSuccess returns true when this issue get labels o k response has a 2xx status code
func (o *IssueGetLabelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this issue get labels o k response has a 3xx status code
func (o *IssueGetLabelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this issue get labels o k response has a 4xx status code
func (o *IssueGetLabelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this issue get labels o k response has a 5xx status code
func (o *IssueGetLabelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this issue get labels o k response a status code equal to that given
func (o *IssueGetLabelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the issue get labels o k response
func (o *IssueGetLabelsOK) Code() int {
	return 200
}

func (o *IssueGetLabelsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/issues/{index}/labels][%d] issueGetLabelsOK %s", 200, payload)
}

func (o *IssueGetLabelsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/issues/{index}/labels][%d] issueGetLabelsOK %s", 200, payload)
}

func (o *IssueGetLabelsOK) GetPayload() []*models.Label {
	return o.Payload
}

func (o *IssueGetLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIssueGetLabelsNotFound creates a IssueGetLabelsNotFound with default headers values
func NewIssueGetLabelsNotFound() *IssueGetLabelsNotFound {
	return &IssueGetLabelsNotFound{}
}

/*
IssueGetLabelsNotFound describes a response with status code 404, with default header values.

APINotFound is a not found empty response
*/
type IssueGetLabelsNotFound struct {
}

// IsSuccess returns true when this issue get labels not found response has a 2xx status code
func (o *IssueGetLabelsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this issue get labels not found response has a 3xx status code
func (o *IssueGetLabelsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this issue get labels not found response has a 4xx status code
func (o *IssueGetLabelsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this issue get labels not found response has a 5xx status code
func (o *IssueGetLabelsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this issue get labels not found response a status code equal to that given
func (o *IssueGetLabelsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the issue get labels not found response
func (o *IssueGetLabelsNotFound) Code() int {
	return 404
}

func (o *IssueGetLabelsNotFound) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/issues/{index}/labels][%d] issueGetLabelsNotFound", 404)
}

func (o *IssueGetLabelsNotFound) String() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/issues/{index}/labels][%d] issueGetLabelsNotFound", 404)
}

func (o *IssueGetLabelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
